# -*- coding: utf-8 -*-
"""Bailey_Sharon.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pSSDnLnvSXIfvDTkqKTscnCMmcPlJ6oQ
"""

import requests
#import os
from datetime import datetime
uploaded = files.upload()

api_key = '87d845b0b6cf29baa1a73cc34b067a95'
location = input("Enter the city name: ")
uploaded = files.upload()

complete_api_link = "https://api.openweathermap.org/data/2.5/weather?qs"+location+"&appid="+api_key
api_lik = requests.get(complete_api_link)
api_data = api_link.json()
uploaded = files.upload()

#create variables to store and display data
temp_city =((api_data['main']['temp']) - 273.15)
weather_desc = api_data['weather'][0]['description']
hmdt = api_data['main']['humidity']
wind_spd = api_data['wind']['speed']
date_time =datetime.now().strftime("%d %b %Y | %I:%M:%S %p")
uploaded = files.upload()

print("-------------------------------------------------------------")
print("Weather Stats for - {} || {} ",format(location.upper(), date_time))
print("-------------------------------------------------------------")
uploaded = files.upload()

print("Current temperature is: {:.2f} deg C".format(temp_city))
print("Current weather desc :",weather_desc)
print("Current Humidity     :",hmdt, '%')
print("Current wind speed   :",wind_spd,'kmph')
uploaded = files.upload()